### ISSUE TITLE
Support for codestar

### ISSUE THREAD

**Issue by asufian97** [varunsridharan/css-spinners#2]
Can you help me please?

**Comment by varunsridharan** [comment]
Hi
What kind of help do you need from me ?

**Comment by asufian97** [comment]
thanks for reply,
i try to add this code on cs-framwork.js but it won't work,
https://github.com/Codestar/codestar-framework/issues/547

**Comment by asufian97** [comment]
> Hi
> What kind of help do you need from me ?

are you there sir?

**Comment by varunsridharan** [comment]
Hi
Yes I am still here. I don't provide support codestar anymore. Since I already developed a wp rapid development Framework which does incldues all of codestar features. And more

**Comment by asufian97** [comment]
actually just for nested group. i have seen you did it but i can't do.

**Comment by varunsridharan** [comment]
@asufian97 Yes ofcourse i did pushed some updates to CodeStar since. there was no proper update from them. so i decided to develop my own open source framework called [WPOnion](https://github.com/wponion/wponion)
